### ISSUE TITLE
test failures on 64-bit big-endian: g_str_has_prefix: assertion 'str != NULL' failed

### ISSUE THREAD

**Issue by smcv** [ostreedev/ostree#1640]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902209

ostree 2018.6 has test failures on s390x and some unofficial ("ports") architectures, probably involving the newly-non-experimental Avahi support. s390x is a representative example:

```
PASS: tests/test-repo-finder-config 1 /repo-finder-config/init
PASS: tests/test-repo-finder-config 2 /repo-finder-config/no-configs
ERROR: tests/test-repo-finder-config - Bail out! GLib-FATAL-CRITICAL: g_str_has_prefix: assertion 'str != NULL' failed

# OSTree-DEBUG: ostree_repo_finder_resolve_all_async: Resolving refs [(org.example.Collection0, exampleos/x86_64/ref0), (org.example.Collection0, exampleos/x86_64/ref1), (org.example.Collection1, exampleos/x86_64/ref1), (org.example.Collection1, exampleos/x86_64/ref2), (org.example.Collection2, exampleos/x86_64/ref3)] with finders [OstreeRepoFinderConfig]
# OSTree-DEBUG: ostree_repo_finder_config_resolve_async: Checking 21474836480 remotes
# OSTree-DEBUG: Resolved ref (org.example.Collection0, exampleos/x86_64/ref0) to remote ?remote0?.
# OSTree-DEBUG: Resolved ref (org.example.Collection0, exampleos/x86_64/ref1) to remote ?remote0?.
# OSTree-DEBUG: Resolved ref (org.example.Collection0, exampleos/x86_64/ref0) to remote ?remote0-copy?.
# OSTree-DEBUG: Resolved ref (org.example.Collection0, exampleos/x86_64/ref1) to remote ?remote0-copy?.
# OSTree-DEBUG: Resolved ref (org.example.Collection1, exampleos/x86_64/ref2) to remote ?remote1?.
# OSTree-DEBUG: Ignoring remote ?remote1-bad-copy? due to it not advertising any of the requested refs.
# OSTree-DEBUG: Ignoring remote ?remote2? due to no valid collection ID being configured for it: Invalid collection ID (null)
Bail out! GLib-FATAL-CRITICAL: g_str_has_prefix: assertion 'str != NULL' failed
ERROR: tests/test-repo-finder-config - Bail out! GLib-FATAL-CRITICAL: g_str_has_prefix: assertion 'str != NULL' failed
```

```
ERROR: tests/test-find-remotes.sh - too few tests run (expected 1, got 0)
ERROR: tests/test-find-remotes.sh - exited with status 133 (terminated by signal 5?)

+ env LD_PRELOAD=/<<PKGBUILDDIR>>/tests/libreaddir-rand.so ostree --repo=local find-remotes --finders=config org.example.AppsCollection app1

(ostree find-remotes:20691): GLib-CRITICAL **: 23:37:14.198: g_str_has_prefix: assertion 'str != NULL' failed
/<<PKGBUILDDIR>>/tests/test-find-remotes.sh: line 89: 20691 Trace/breakpoint trap   ${CMD_PREFIX} ostree --repo=$repo find-remotes --finders=config org.example.AppsCollection app1 > find
```

Unfortunately 32-bit architectures were failing to build due to the format string mismatch you fixed in 1174d9f, so weren't tested yet. I've prepared an upload with 1174d9f applied, which should give us a better picture of which architectures have this test failure. Right now we have:

```
          little-endian                         big-endian

32-bit    armel armhf i386 mipsel               mips powerpc(spe) sparc64:
          sh4 x32:                              fails: needs 1174d9f
          fails: needs 1174d9f

64-bit    amd64 arm64 mips64el ppc64el          s390x hppa ppc64:
          alpha ia64 riscv64:                   tests fail: this bug
          successful
```

which looks suspiciously like correlation with big-endian architectures. If that theory is correct, arm* i386 mipsel sh4 and x32 will succeed after the format string is fixed, but mips powerpc(spe) and sparc64 will continue to fail their tests due to this bug.

**Comment by smcv** [comment]
Latest build logs can (always) be found at https://buildd.debian.org/status/package.php?p=ostree (2018.6-1 is the version that needs 1174d9f applied, and builds of 2018.6-2 should be attempted in the next few hours). At some point I'll try to reproduce the test failure on a Debian-developer-accessible machine of one of the affected architectures and get a backtrace from the warning.

**Comment by smcv** [comment]
The build logs for 2018.6-2 say my theory wasn't quite right: this bug seems to affect all 64-bit big-endian architectures in Debian, but not 32-bit or little-endian architectures. Hopefully that information will help to track down the cause.

**Comment by smcv** [comment]
Backtrace (frames 1-4 are the assertion failure):

```
#5  0x000003ff94f77746 in g_str_has_prefix (str=str@entry=0x0, prefix=prefix@entry=0x3ff95410262 "file://")
    at ../../../../glib/gstrfuncs.c:2874
#6  0x000003ff953ac7d2 in _ostree_repo_remote_name_is_file (remote_name=0x0) at src/libostree/ostree-repo.c:769
#7  0x000003ff953ac7d2 in ostree_repo_get_remote_option (self=0x13a787020 [OstreeRepo], 
    self@entry=<error reading variable: value has been optimized out>, remote_name=0x0, option_name=<optimized out>, 
    option_name@entry=0x3ff9540ff4a "collection-id", default_value=default_value@entry=0x0, out_value=out_value@entry=0x3fffc27d930, error=0x3fffc27d918) at src/libostree/ostree-repo.c:801
#8  0x000003ff953fbdbe in ostree_repo_finder_config_resolve_async (finder=0x13a783b60, refs=0x13a788940, parent_repo=<optimized out>, cancellable=<optimized out>, callback=<optimized out>, user_data=0x13a7898d0)
    at src/libostree/ostree-repo-finder-config.c:123
#9  0x000003ff953f833c in ostree_repo_finder_resolve_all_async (finders=<optimized out>, refs=0x13a788940, parent_repo=0x13a787020 [OstreeRepo], cancellable=0x0, callback=<optimized out>, user_data=0x13a789800)
    at src/libostree/ostree-repo-finder.c:315
#10 0x000003ff953c4508 in ostree_repo_find_remotes_async (self=0x13a787020 [OstreeRepo], refs=0x13a788940, options=options@entry=0x0, finders=0x13a788d40, progress=progress@entry=0x0, cancellable=0x0, callback=0x120f18e40 <get_result_cb>, user_data=0x3fffc27dc88) at src/libostree/ostree-repo-pull.c:4984
#11 0x0000000120f1936e in ostree_builtin_find_remotes (argc=<optimized out>, argv=<optimized out>, invocation=<optimized out>, cancellable=0x0, error=0x3fffc27de18) at src/ostree/ot-builtin-find-remotes.c:289
#12 0x0000000120f21272 in ostree_run (argc=<optimized out>, argv=<optimized out>, commands=0x120f40010 <commands>, res_error=0x3fffc27dee0) at src/ostree/ot-main.c:202
#13 0x0000000120f13c3a in main (argc=<optimized out>, argv=0x3fffc27e118) at src/ostree/main.c:138
```
