### ISSUE TITLE
Automotive Stream Distribution builds failing

### ISSUE THREAD

**Issue by ericcurtin** [ostreedev/ostree#3217]
We are having a lot of those on the ostree images in the pipeline:

```
error: Postprocessing and committing: Finalizing rootfs: During kernel processing: renaming boot: unlinkat(boot): Directory not empty
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.ostree.commit", line 124, in <module>
    r = main(args["inputs"],
  File "/run/osbuild/bin/org.osbuild.ostree.commit", line 111, in main
    subprocess.run(argv,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rpm-ostree', 'compose', 'commit', '--repo=/run/osbuild/tree/repo', '--add-metadata-string=version=1', '--add-metadata-string=rpmostree.inputhash=a79640dcc351adb1198eb96a38843103ac243bf2f9d55f8f5d055e681742c8b8', '--write-composejson-to=/run/osbuild/tree/compose.json', '/tmp/tmpb1dfd_rl.json', '/run/osbuild/tree/tmpfsmmc_tr']' returned non-zero exit status 1.
```

**Comment by cgwalters** [comment]
That's an rpm-ostree issue, not an ostree issue.  Presumably this is a regression, i.e. things worked before?  Please include as much information as you can, like links to the pipeline logs, the specific version of rpm-ostree etc. when re-filing a bug there.

**Comment by alexlarsson** [comment]
The pipeline logs are here: 
https://artifacts.dev.testing-farm.io/3e5934e5-63b6-40ac-b343-a7ba2af369b1/work-create-osbuildxflyeloh/plans/create-osbuild/execute/data/guest/default-0/Create-osbuild-image-2/output.txt
