### ISSUE TITLE
exception in non-404 error paths

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#373]
See https://bugzilla.redhat.com/show_bug.cgi?id=1342168#c18

**Comment by Mathnerd314** [comment]
I'm guessing that this is two problems:
* fetch data isn't freed properly (should be fixed by https://github.com/ostreedev/ostree/pull/353/commits/01fc763c69909b621843f445edbbb37d4e950b3a)
* An HTTP error (e.g. the 403) doesn't cancel the fetch, so it keeps going

**Comment by cgwalters** [comment]
I managed to get the following trace:

```
(gdb) t a a bt

Thread 3 (Thread 0x7f1e7ebb6700 (LWP 24909)):
#0  0x00007f1e8258cbcd in poll () at /lib64/libc.so.6
#1  0x00007f1e82d6e0cc in g_main_context_iterate.isra.24 () at /lib64/libglib-2.0.so.0
#2  0x00007f1e82d6e1ec in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007f1e82d6e229 in glib_worker_main () at /lib64/libglib-2.0.so.0
#4  0x00007f1e82d931b5 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007f1e82869dc5 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f1e8259721d in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f1e7c0e5700 (LWP 24910)):
#0  0x00007f1e82591999 in syscall () at /lib64/libc.so.6
#1  0x00007f1e82db0b6e in g_cond_wait_until () at /lib64/libglib-2.0.so.0
#2  0x00007f1e82d43361 in g_async_queue_pop_intern_unlocked () at /lib64/libglib-2.0.so.0
#3  0x00007f1e82d93b12 in g_thread_pool_thread_proxy () at /lib64/libglib-2.0.so.0
#4  0x00007f1e82d931b5 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007f1e82869dc5 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f1e8259721d in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f1e849cd840 (LWP 24907)):
#0  0x00007f1e82db08e5 in g_mutex_lock () at /lib64/libglib-2.0.so.0
#1  0x00007f1e82d6c268 in g_source_destroy_internal () at /lib64/libglib-2.0.so.0
#2  0x00007f1e83678358 in soup_session_dispose () at /lib64/libsoup-2.4.so.1
#3  0x00007f1e830465f2 in g_object_unref () at /lib64/libgobject-2.0.so.0
#4  0x00007f1e843c8586 in thread_closure_unref (thread_closure=0x9288f0) at src/libostree/ostree-fetcher.c:143
#5  0x00007f1e843c9545 in _ostree_fetcher_finalize (object=0x92d730) at src/libostree/ostree-fetcher.c:537
#6  0x00007f1e830466e4 in g_object_unref () at /lib64/libgobject-2.0.so.0
#7  0x00007f1e843a719b in ostree_repo_pull_with_options (self=<optimized out>, remote_name_or_baseurl=<optimized out>, options=<optimized out>, progress=progress@entry=0x0, cancellable=cancellable@entry=0x0, error=error@entry=0x7ffc6efd5958)
    at src/libostree/ostree-repo-pull.c:2869
#8  0x0000000000419a2d in ostree_builtin_pull (argc=3, argv=0x7ffc6efd5aa8, cancellable=0x0, error=0x7ffc6efd5958) at src/ostree/ot-builtin-pull.c:260
#9  0x00000000004128f0 in ostree_run (argc=5, argc@entry=6, argv=argv@entry=0x7ffc6efd5aa8, commands=commands@entry=0x629f60 <commands>, res_error=res_error@entry=0x7ffc6efd59a8) at src/ostree/ot-main.c:209
#10 0x000000000040b12f in main (argc=6, argv=0x7ffc6efd5aa8) at src/ostree/main.c:78
```

It doesn't happen often at least for me.  What seems to be happening here is that the final unref is in the main thread but the unreference code assumes the final drop is really in the worker thread?

I think we can fix this by joining the worker thread first.  Investigating.

**Comment by cgwalters** [comment]
I tried this in https://github.com/ostreedev/ostree/pull/383 but ended up with different crashes, current stack is:

```
(gdb) t a a bt

Thread 4 (Thread 0x7fd6251ac700 (LWP 32240)):
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#0  0x00007fd628b82bcd in poll#1  0x00007fd6293640cc in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0x127a0b0, timeout=-1, context=0x1279530) at gmain.c:4135
#2  0x00007fd6293640cc in g_main_context_iterate (context=context@entry=0x1279530, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3835
#3  0x00007fd6293641ec in g_main_context_iteration (context=0x1279530, may_block=may_block@entry=1) at gmain.c:3901
#4  0x00007fd629364229 in glib_worker_main (data=<optimized out>) at gmain.c:5672
#5  0x00007fd6293891b5 in g_thread_proxy (data=0x1276850) at gthread.c:780
#6  0x00007fd628e5fdc5 in start_thread (arg=0x7fd6251ac700) at pthread_create.c:308
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#7  0x00007fd628b8d21d in clone
Thread 3 (Thread 0x7fd62afc3840 (LWP 32238)):
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#0  0x00007fd628b87999 in syscall#1  0x00007fd6293356da in g_mutex_unlock_slowpath (mutex=<optimized out>, prev=<optimized out>) at gthread-posix.c:1328
#2  0x00007fd6293a690e in g_mutex_unlock (mutex=<optimized out>) at gthread-posix.c:1348
#3  0x00007fd629364523 in g_main_loop_quit (loop=<optimized out>) at gmain.c:4065
#4  0x00007fd62a9bf636 in _ostree_fetcher_finalize (object=0x1272730 [OstreeFetcher]) at src/libostree/ostree-fetcher.c:546
#5  0x00007fd62963c6e4 in g_object_unref (_object=0x1272730) at gobject.c:3183
#6  0x00007fd62a99d28b in ostree_repo_pull_with_options (self=<optimized out>, remote_name_or_baseurl=<optimized out>, options=<optimized out>, progress=<optimized out>, cancellable=0x0, error=<optimized out>) at src/libostree/ostree-repo-pull.c:2869
#7  0x00000000004199fd in ostree_builtin_pull (argc=3, argv=0x7ffe1b44b7d8, cancellable=0x0, error=0x7ffe1b44b688) at src/ostree/ot-builtin-pull.c:245
#8  0x00000000004128c0 in ostree_run (argc=5, argv=0x7ffe1b44b7d8, commands=0x629f60 <commands>, res_error=0x7ffe1b44b6d8) at src/ostree/ot-main.c:205
#9  0x000000000040b0ff in main (argc=6, argv=0x81) at src/ostree/main.c:74

Thread 2 (Thread 0x7fd6226db700 (LWP 32241)):
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#0  0x00007fd628b87999 in syscall#1  0x00007fd6293a6b6e in g_cond_wait_until (cond=cond@entry=0x12782e8, mutex=mutex@entry=0x12782e0, end_time=end_time@entry=303674886905) at gthread-posix.c:1441
#2  0x00007fd629339361 in g_async_queue_pop_intern_unlocked (queue=0x12782e0, wait=wait@entry=1, end_time=303674886905) at gasyncqueue.c:422
#3  0x00007fd629339958 in g_async_queue_timeout_pop_unlocked (queue=<optimized out>, timeout=timeout@entry=500000) at gasyncqueue.c:570
#4  0x00007fd629389b12 in g_thread_pool_thread_proxy (pool=0x1279040) at gthreadpool.c:262
#5  0x00007fd629389b12 in g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:296
#6  0x00007fd6293891b5 in g_thread_proxy (data=0x1280c00) at gthread.c:780
#7  0x00007fd628e5fdc5 in start_thread (arg=0x7fd6226db700) at pthread_create.c:308
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#8  0x00007fd628b8d21d in clone
Thread 1 (Thread 0x7fd6259ad700 (LWP 32239)):
#0  0x00007fd6293a68e5 in g_mutex_lock (mutex=mutex@entry=0xa0a0a0a0a0a0a0a0) at gthread-posix.c:1335
#1  0x00007fd629362268 in g_source_destroy_internal (source=0x1480390, context=0xa0a0a0a0a0a0a0a0, have_lock=0) at gmain.c:1188
#2  0x00007fd6293625b5 in g_source_destroy (source=<optimized out>) at gmain.c:1256
#3  0x00007fd629c6e358 in soup_session_dispose (object=0x127e110 [SoupSessionAsync]) at soup-session.c:328
#4  0x00007fd62963c5f2 in g_object_unref (_object=0x127e110) at gobject.c:3146
#5  0x00007fd62a9be676 in thread_closure_unref (thread_closure=0x126d8f0) at src/libostree/ostree-fetcher.c:143
#6  0x00007fd62a9be85f in ostree_fetcher_session_thread (data=0x126d8f0) at src/libostree/ostree-fetcher.c:486
#7  0x00007fd6293891b5 in g_thread_proxy (data=0x1276800) at gthread.c:780
#8  0x00007fd628e5fdc5 in start_thread (arg=0x7fd6259ad700) at pthread_create.c:308
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#9  0x00007fd628b8d21d in clone(gdb) 

```

**Comment by hadess** [comment]
I can reproduce this easily on the CHIP, a $9 ARM board. Just run the test suite with core dumps enabled. I gathered 8 coredumps that matched the above problem.

**Comment by mbarnes** [comment]
```
Thread 1 (Thread 0x7fd6259ad700 (LWP 32239)):
#0  0x00007fd6293a68e5 in g_mutex_lock (mutex=mutex@entry=0xa0a0a0a0a0a0a0a0) at gthread-posix.c:1335
#1  0x00007fd629362268 in g_source_destroy_internal (source=0x1480390, context=0xa0a0a0a0a0a0a0a0, have_lock=0) at gmain.c:1188
```
The `context` address here jumped out at me.  Perhaps the `GMainContext` is already freed?  But there's no ref-counting errors on it in the fetcher code AFAICS.

**Comment by cgwalters** [comment]
Took about 200 runs but I got this once:

```
(gdb) t a a bt

Thread 3 (Thread 0x7f813a774700 (LWP 29673)):
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#0  0x00007f813e14abcd in poll#1  0x00007f813e92c0cc in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0x2388590, timeout=-1, context=0x23889c0) at gmain.c:4135
#2  0x00007f813e92c0cc in g_main_context_iterate (context=context@entry=0x23889c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3835
#3  0x00007f813e92c1ec in g_main_context_iteration (context=0x23889c0, may_block=may_block@entry=1) at gmain.c:3901
#4  0x00007f813e92c229 in glib_worker_main (data=<optimized out>) at gmain.c:5672
#5  0x00007f813e9511b5 in g_thread_proxy (data=0x2385850) at gthread.c:780
#6  0x00007f813e427dc5 in start_thread (arg=0x7f813a774700) at pthread_create.c:308
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#7  0x00007f813e15521d in clone
Thread 2 (Thread 0x7f8137ca3700 (LWP 29674)):
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#0  0x00007f813e14f999 in syscall#1  0x00007f813e96eb6e in g_cond_wait_until (cond=cond@entry=0x237c5d8, mutex=mutex@entry=0x237c5d0, end_time=end_time@entry=348074669338) at gthread-posix.c:1441
#2  0x00007f813e901361 in g_async_queue_pop_intern_unlocked (queue=0x237c5d0, wait=wait@entry=1, end_time=348074669338) at gasyncqueue.c:422
#3  0x00007f813e901958 in g_async_queue_timeout_pop_unlocked (queue=<optimized out>, timeout=timeout@entry=500000) at gasyncqueue.c:570
#4  0x00007f813e951b12 in g_thread_pool_thread_proxy (pool=0x2387ed0) at gthreadpool.c:262
#5  0x00007f813e951b12 in g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:296
#6  0x00007f813e9511b5 in g_thread_proxy (data=0x238fc00) at gthread.c:780
#7  0x00007f813e427dc5 in start_thread (arg=0x7f8137ca3700) at pthread_create.c:308
Python Exception <type 'exceptions.RuntimeError'> Cannot locate object file for block.: 
#8  0x00007f813e15521d in clone
Thread 1 (Thread 0x7f8140588840 (LWP 29671)):
#0  0x00007f813e0945f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f813e095ce8 in __GI_abort () at abort.c:90
#2  0x00007f813e0db515 in free_check (ar_ptr=<optimized out>, ptr=<optimized out>, str=<optimized out>, action=<optimized out>) at malloc.c:5017
#3  0x00007f813e0db515 in free_check (mem=<optimized out>, caller=<optimized out>) at hooks.c:281
#4  0x00007f813e93149e in g_free (mem=0xffffffff) at gmem.c:189
#5  0x00007f813e91a752 in g_hash_table_remove_all_nodes (hash_table=0x2383360<error reading variable: Cannot access memory at address 0x4>, notify=<optimized out>, destruction=<optimized out>) at ghash.c:548
#6  0x00007f813e91b07a in g_hash_table_unref (destruction=1, notify=1, hash_table=0x2383360<error reading variable: Cannot access memory at address 0x4>) at ghash.c:1093
#7  0x00007f813e91b07a in g_hash_table_unref (hash_table=hash_table@entry=0x2383360<error reading variable: Cannot access memory at address 0x4>) at ghash.c:1097
#8  0x00007f813ff6439c in ostree_repo_pull_with_options (_ptr=<synthetic pointer>) at /usr/include/glib-2.0/glib/glib-autocleanups.h:48
#9  0x00007f813ff6439c in ostree_repo_pull_with_options (self=<optimized out>, remote_name_or_baseurl=<optimized out>, options=<optimized out>, progress=<optimized out>, cancellable=0x0, error=<optimized out>)
    at src/libostree/ostree-repo-pull.c:2189
#10 0x00000000004199fd in ostree_builtin_pull (argc=3, argv=0x7ffef6cbd1d8, cancellable=0x0, error=0x7ffef6cbd088) at src/ostree/ot-builtin-pull.c:240
#11 0x00000000004128c0 in ostree_run (argc=5, argv=0x7ffef6cbd1d8, commands=0x629f60 <commands>, res_error=0x7ffef6cbd0d8) at src/ostree/ot-main.c:167
#12 0x000000000040b0ff in glnx_cleanup_close_fdp (fdp=<optimized out>) at ./libglnx/glnx-local-alloc.h:201
#13 0x0000000000000000 in  ()
```

Still trying to reproduce in valgrind.

**Comment by cgwalters** [comment]
Ran valgrind overnight, got:

```
==25466== Invalid read of size 8
==25466==    at 0x6667FC5: g_source_destroy (gmain.c:1224)
==25466==    by 0x5DFF357: soup_session_dispose (soup-session.c:328)
==25466==    by 0x63E4AD1: g_object_unref (gobject.c:3133)
==25466==    by 0x4E852E5: thread_closure_unref (ostree-fetcher.c:143)
==25466==    by 0x4E854CE: ostree_fetcher_session_thread (ostree-fetcher.c:486)
==25466==    by 0x668F4F4: g_thread_proxy (gthread.c:764)
==25466==    by 0x6C04DC4: start_thread (pthread_create.c:308)
==25466==    by 0x6F0FCEC: clone (clone.S:113)
==25466==  Address 0xa8e1480 is 32 bytes inside a block of size 96 free'd
==25466==    at 0x4C2AD17: free (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==25466==    by 0x666F37E: g_free (gmem.c:190)
==25466==    by 0x6666C0D: g_source_unref_internal (gmain.c:2032)
==25466==    by 0x66698C7: g_main_dispatch (gmain.c:3136)
==25466==    by 0x66698C7: g_main_context_dispatch (gmain.c:3708)
==25466==    by 0x6669AF7: g_main_context_iterate.isra.24 (gmain.c:3779)
==25466==    by 0x6669DC9: g_main_loop_run (gmain.c:3973)
==25466==    by 0x4E854BD: ostree_fetcher_session_thread (ostree-fetcher.c:482)
==25466==    by 0x668F4F4: g_thread_proxy (gthread.c:764)
==25466==    by 0x6C04DC4: start_thread (pthread_create.c:308)
==25466==    by 0x6F0FCEC: clone (clone.S:113)
```

**Comment by cgwalters** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=768567

**Comment by Mathnerd314** [comment]
It looks like `pull_data->cancellable` is never initialized! So when `check_outstanding_requests_handle_error` calls `g_cancellable_cancel`:
> If cancellable is NULL, this function returns immediately for convenience.

This might explain the long list of GLib-GIO-CRITICAL's. The crashes and the criticals are probably two different bugs though.

**Comment by cgwalters** [comment]
Hmm, we don't actually invoke `g_cancellable_cancel()` AFAICS?  I'm not sure we should either.  

Currently `pull_termination_condition()` does:
```
if (pull_data->caught_error)
  return TRUE;
```
which I believe should be sufficient to abort fetches that catch 403.
