### ISSUE TITLE
pull: Racy assert: ostree_checksum_inplace_to_bytes: assertion failed: (checksum[j])

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree#583]
I had to run quite a while to catch this:

```
+ . /home/walters/src/github/ostreedev/ostree.pull-race/tests/pull-test.sh
++ set -euo pipefail
++ echo 1..13
++ repo_init
++ cd /var/tmp/tap-test.lj2rm9
e9d4050dc755c023526c6b49a05ef2e4c127b4e1dc800cd6567d44ba159719d3
++ rm repo -rf
++ mkdir repo
++ env LD_PRELOAD=/home/walters/src/github/ostreedev/ostree.pull-race/tests/libreaddir-rand.so ostree --repo=repo init
+++ cat httpd-address
++ env LD_PRELOAD=/home/walters/src/github/ostreedev/ostree.pull-race/tests/libreaddir-rand.so ostree --repo=repo remote add --set=gpg-verify=false origin http://127.0.0.1:33749/ostree/gnomerepo
++ env LD_PRELOAD=/home/walters/src/github/ostreedev/ostree.pull-race/tests/libreaddir-rand.so ostree --repo=repo pull origin main
**
OSTree:ERROR:src/libostree/ostree-core.c:1234:ostree_checksum_inplace_to_bytes: assertion failed: (checksum[j])
```

**Comment by cgwalters** [comment]
Running another loop overnight got me back in an infinite loop on a hash table, just like https://github.com/ostreedev/ostree/pull/383#issuecomment-231160278

Retrying with an ASAN build.

**Comment by smcv** [comment]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007fbdf4dc640a in __GI_abort () at abort.c:89
#2  0x00007fbdf56787f6 in g_assertion_message (domain=domain@entry=0x7fbdf6277799 "OSTree", 
    file=file@entry=0x7fbdf62773d0 "/home/smcv/src/ostree/src/libostree/ostree-core.c", 
    line=line@entry=1234, 
    func=func@entry=0x7fbdf6277b40 <__func__.30225> "ostree_checksum_inplace_to_bytes", 
    message=message@entry=0x55d9acdd1c90 "assertion failed: (checksum[j])")
    at /home/smcv/src/glib/glib/gtestutils.c:2433
#3  0x00007fbdf5678846 in g_assertion_message_expr (
    domain=domain@entry=0x7fbdf6277799 "OSTree", 
    file=file@entry=0x7fbdf62773d0 "/home/smcv/src/ostree/src/libostree/ostree-core.c", 
    line=line@entry=1234, 
    func=func@entry=0x7fbdf6277b40 <__func__.30225> "ostree_checksum_inplace_to_bytes", 
    expr=expr@entry=0x7fbdf6277895 "checksum[j]") at /home/smcv/src/glib/glib/gtestutils.c:2456
#4  0x00007fbdf62301fa in ostree_checksum_inplace_to_bytes (
    checksum=checksum@entry=0x55d9acddf88f "", buf=buf@entry=0x7ffdfded84f0 "")
    at /home/smcv/src/ostree/src/libostree/ostree-core.c:1234
#5  0x00007fbdf62311ae in _ostree_get_relative_static_delta_path (from=from@entry=0x0, 
    to=to@entry=0x55d9acddf88f "", target=target@entry=0x7fbdf627798d "superblock")
    at /home/smcv/src/ostree/src/libostree/ostree-core.c:1528
#6  0x00007fbdf62314af in _ostree_get_relative_static_delta_superblock_path (
    from=from@entry=0x0, to=to@entry=0x55d9acddf88f "")
    at /home/smcv/src/ostree/src/libostree/ostree-core.c:1568
#7  0x00007fbdf6245c51 in request_static_delta_superblock_sync (
    pull_data=pull_data@entry=0x7ffdfded8660, from_revision=0x0, 
    to_revision=to_revision@entry=0x55d9acddf88f "", 
    out_delta_superblock=out_delta_superblock@entry=0x7ffdfded8610, 
    cancellable=cancellable@entry=0x0, error=error@entry=0x7ffdfded8a28)
    at /home/smcv/src/ostree/src/libostree/ostree-repo-pull.c:1434
#8  0x00007fbdf624afee in ostree_repo_pull_with_options (self=<optimized out>, 
    remote_name_or_baseurl=0x55d9acdb3bb0 "origin", options=options@entry=0x55d9acdb8f50, 
    progress=progress@entry=0x0, cancellable=cancellable@entry=0x0, 
    error=error@entry=0x7ffdfded8a28)
    at /home/smcv/src/ostree/src/libostree/ostree-repo-pull.c:2963
#9  0x000055d9ac46fa31 in ostree_builtin_pull (argc=<optimized out>, argv=<optimized out>, 
    cancellable=0x0, error=0x7ffdfded8a28)
    at /home/smcv/src/ostree/src/ostree/ot-builtin-pull.c:296
#10 0x000055d9ac46713d in ostree_run (argc=<optimized out>, argv=<optimized out>, 
    commands=0x55d9ac682fc0 <commands>, res_error=0x7ffdfded8a78)
    at /home/smcv/src/ostree/src/ostree/ot-main.c:204
#11 0x000055d9ac45eef3 in main (argc=5, argv=0x7ffdfded8b78)
    at /home/smcv/src/ostree/src/ostree/main.c:78
```

**Comment by cgwalters** [comment]
Haven't seen this in a while.  I believe the libsoup patches address this.  There's also now the libcurl backend which I increasingly recommend by default.
